version: "2.0"

services:
  db:
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=8Fny?aXEFkh9ePA3
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    networks:
      estiam_network:

  auth-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - "staticfiles-data:/var/www/static"
      - "media-data:/var/www/media"
    depends_on:
      - db
    ports:
      - "8030:8030"
    networks:
      estiam_network:

networks:
  estiam_network:
    external: true

volumes:
  postgres-data:
  staticfiles-data:
  media-data:
