
wait_db:
	python manage.py wait_for_db

migrate:
	python manage.py makemigrations && python manage.py migrate --noinput

flushdb:
	python manage.py flush -y

collectstatic:
	python manage.py collectstatic --noinput
